site_name: Blockchain Web Services
site_url: https://docs.bws.ninja
site_description: BWS Documentation - Simplifying blockchain integration through a
  unified REST API
docs_dir: site-content
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences: {}
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
- tables
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
- search
- glightbox
extra_css:
- stylesheets/extra.css
nav:
- Welcome!: README.md
- Quick Start: quick-start.md
- Platform Fees: platform-fees/README.md
- API How Tos:
  - Overview: api-how-tos/README.md
  - API Endpoint: api-how-tos/api-endpoint.md
  - Authentication:
    - Overview: api-how-tos/authentication/README.md
    - Get your API Key: api-how-tos/authentication/get-your-api-key.md
  - Main API Methods:
    - Overview: api-how-tos/main-api-methods/README.md
    - '''call'' API Method': api-how-tos/main-api-methods/call-api-method.md
    - '''fetch'' API Method': api-how-tos/main-api-methods/fetch-api-method.md
  - API Responses:
    - Overview: api-how-tos/api-responses/README.md
    - Error Status Codes: api-how-tos/api-responses/error-status-codes.md
- Certificate Of Trust: certificate-of-trust.md
- Media Assets:
  - Overview: media-assets/README.md
  - BWS Logo: media-assets/bws-logo.md
  - Blurbs:
    - Overview: media-assets/blurbs/README.md
    - BWS.IPFS.Upload: media-assets/blurbs/BWS.IPFS.Upload/README.md
    - BWS.Blockchain.Save: media-assets/blurbs/BWS.Blockchain.Save/README.md
    - BWS.Blockchain.Hash: media-assets/blurbs/BWS.Blockchain.Hash/README.md
    - BWS.NFT.zK: media-assets/blurbs/BWS.NFT.zK/README.md
    - Blockchain Badges: media-assets/blurbs/BWS.Blockchain.Badges/README.md
    - FAN Game Cube: media-assets/blurbs/BWS.NFT.GameCube/README.md
    - ESG Credits: media-assets/blurbs/BWS.ESG.Credits/README.md
    - X Bot: media-assets/blurbs/BWS.X.Bot/README.md
  - Snapshots:
    - Overview: media-assets/snapshots/README.md
    - Blockchain Badges: media-assets/snapshots/BWS.Blockchain.Badges/README.md
    - FAN Game Cube: media-assets/snapshots/BWS.NFT.GameCube/README.md
    - X Bot: media-assets/snapshots/BWS.X.Bot/README.md
- PLATFORM APIs:
  - BWS.IPFS.Upload: solutions/bws.ipfs.upload/README.md
  - BWS.Blockchain.Save:
    - Overview: solutions/bws.blockchain.save/README.md
    - Solution Overview: solutions/bws.blockchain.save/solution-overview.md
    - Operations: solutions/bws.blockchain.save/operations.md
  - BWS.Blockchain.Hash:
    - Overview: solutions/bws.blockchain.hash/README.md
    - Solution Overview: solutions/bws.blockchain.hash/solution-overview.md
    - Operations: solutions/bws.blockchain.hash/operations.md
  - BWS.NFT.zK:
    - Overview: solutions/bws.nft.zk/README.md
    - Solution Overview: solutions/bws.nft.zk/solution-overview/README.md
    - Operations: solutions/bws.nft.zk/operations/README.md
    - NFT Attributes (traits): solutions/bws.nft.zk/nft-attributes-traits.md
- Marketplace Solutions:
  - Blockchain Badges:
    - Overview: marketplace-solutions/bws.blockchain.badges/README.md
    - Badges User Interface: marketplace-solutions/bws.blockchain.badges/badges-user-interface.md
    - Badges API:
      - Overview: marketplace-solutions/bws.blockchain.badges/badges-api/README.md
      - Issuers: marketplace-solutions/bws.blockchain.badges/badges-api/issuers.md
      - Badges: marketplace-solutions/bws.blockchain.badges/badges-api/badges.md
      - Awards (Credentials): marketplace-solutions/bws.blockchain.badges/badges-api/awards-credentials.md
  - FAN Game Cube:
    - Overview: marketplace-solutions/bws.nft.gamecube/README.md
    - FAN Game Overview: marketplace-solutions/bws.nft.gamecube/nft-game-overview.md
    - FAN Game Cube API:
      - Overview: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/README.md
      - Calendar: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/calendar.md
      - Field: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/field.md
      - Cubes: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/cubes.md
      - Plays (Field-Calendar): marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/plays-field-calendar.md
      - Match: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/match.md
      - Prizes: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/prizes.md
      - Event Types: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/event-types.md
      - Live Events: marketplace-solutions/bws.nft.gamecube/nft-game-cube-api/live-events.md
  - ESG Credits:
    - Overview: marketplace-solutions/bws.esg.credits/README.md
    - Solution Overview: marketplace-solutions/bws.esg.credits/solution-overview.md
    - ESG Credits API:
      - Overview: marketplace-solutions/bws.esg.credits/esg-credits-api/README.md
      - Taxonomy: marketplace-solutions/bws.esg.credits/esg-credits-api/taxonomy.md
      - Translations: marketplace-solutions/bws.esg.credits/esg-credits-api/translations.md
      - Currencies: marketplace-solutions/bws.esg.credits/esg-credits-api/currencies.md
      - Frameworks: marketplace-solutions/bws.esg.credits/esg-credits-api/frameworks.md
      - Projects: marketplace-solutions/bws.esg.credits/esg-credits-api/projects.md
      - Issuers: marketplace-solutions/bws.esg.credits/esg-credits-api/issuers.md
      - Assets: marketplace-solutions/bws.esg.credits/esg-credits-api/assets.md
      - Investors: marketplace-solutions/bws.esg.credits/esg-credits-api/investors.md
      - Positions: marketplace-solutions/bws.esg.credits/esg-credits-api/positions.md
      - Portfolios: marketplace-solutions/bws.esg.credits/esg-credits-api/portfolios.md
      - Impacts: marketplace-solutions/bws.esg.credits/esg-credits-api/impacts.md
      - Blockchain: marketplace-solutions/bws.esg.credits/esg-credits-api/blockchain.md
      - Users: marketplace-solutions/bws.esg.credits/esg-credits-api/users.md
  - X Bot:
    - Overview: marketplace-solutions/bws.x.bot/README.md
    - X Bot Overview: marketplace-solutions/bws.x.bot/x-bot-overview.md
    - X Bot Installation: marketplace-solutions/bws.x.bot/x-bot-installation.md
    - X Bot Commands:
      - Overview: marketplace-solutions/bws.x.bot/commands/README.md
      - Filter Setup: marketplace-solutions/bws.x.bot/commands/filter-setup.md
      - Basic Commands: marketplace-solutions/bws.x.bot/commands/basic-commands.md
      - Advanced Filtering: marketplace-solutions/bws.x.bot/commands/advanced-filtering.md
      - Project Configuration: marketplace-solutions/bws.x.bot/commands/project-configuration.md
      - Raid Commands: marketplace-solutions/bws.x.bot/commands/raid-commands.md
      - Schedule Management: marketplace-solutions/bws.x.bot/commands/schedule-management.md
      - Calendar & Time: marketplace-solutions/bws.x.bot/commands/calendar-and-time.md
      - Reports: marketplace-solutions/bws.x.bot/commands/reports.md
      - Leaderboard Customization: marketplace-solutions/bws.x.bot/commands/leaderboard-customization.md
      - Topic Management: marketplace-solutions/bws.x.bot/commands/topic-management.md
      - Admin: marketplace-solutions/bws.x.bot/commands/admin.md
      - Subscription & Credits: marketplace-solutions/bws.x.bot/commands/subscription-and-credits.md
    - Getting Support: marketplace-solutions/bws.x.bot/x-bot-support.md
